name: "ASoC DAST Scan"
on:
  workflow_call:
    secrets:
      ASOC_KEY:
        required: true
      ASOC_SECRET:
        required: true
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ASoC DAST Scan
        uses: HCL-TECH-SOFTWARE/appscan-dast-action@v1.0.6
        with:
          baseurl:  https://eu.cloud.appscan.com
          asoc_key: ${{secrets.ASOC_KEY}}
          asoc_secret: ${{secrets.ASOC_SECRET}}
          application_id: 15dad7d4-511e-4c79-883a-d2b788aec9d8
          dynamic_scan_type: dast
          starting_URL: 'https://demo.testfire.net?mode=demo'
          #login_method: userpass
          #login_user: admin
          #login_password: admin
          login_method: recorded
          login_sequence_file: login/seq_demo.dast.config
          network: public
          fail_for_noncompliance: false
          wait_for_analysis: true
